---
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
  - vars.yml

  vars:
    droplets:
      - { name: a4d.lamp.webserver, group: "lamp-webserver" }
      - { name: a4d.lamp.dbserver, group: "lamp-www" }

  tasks:
  - include: droplet.yml

- hosts: do
  remote_user: root
  gather_facts: no

  tasks: 
   - name: Wait for port 22 to become available. 
     local_action: "wait_for port=22 host={{ inventory_hostname }}"